baseURL = "https://blog.miguellopezariza.com/"
languageCode = "es-CO"
title = "Miguel López Ariza"
theme = "bilberry-hugo-theme"
publishDir = "docs"
DefaultContentLanguage = "es"

enableRobotsTXT = true
disqusShortname="blog.miguellopezariza.com"


[params]
   algolia_search    = true
   algolia_appId     = "I7WDR47S3K"
   algolia_apiKey    = "41a21ce5e1edd6a9b6fc160d3ca45fb8"
   algolia_indexName = "blog.miguellopezariza.com"
   algolia_currentLanguageOnly = false

   googleAnalyticsID = "G-BHYMJ90XJ7"
   author = "Miguel López Ariza"
   description = "Blog dedicado a tocar temas relacionados con la programación y mi labor diaria como trabajador, estudiante y profesor"
   keywords = "blog,laravel,php,angular,ionic,developer,desarrollador,programador"

   avatarEmail = "lopezarizamiguel@gmail.com"
   subtitle = "Hola, te compartiré un poco de mi experiencia como programador!"

   showSocialMedia = true
  
   socialMediaLinks = [
      { link = "https://github.com/parrotsoft", icon = "fab fa-github" },
      { link = "https://www.linkedin.com/in/mlopezariza", icon = "fab fa-linkedin-in" },
      { link = "https://twitter.com/miguelopeza", icon = "fab fa-twitter" },
      { link = "https://www.youtube.com/channel/UCoaqC95Z7XQBerrFTYf3Rbg", icon = "fab fa-youtube" }
    ]

       
    copyrightBy = "by Miguel Lopez Ariza"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightUrl = "https://github.com/parrotsoft"
    creditsText = "Miguel Lopez Ariza"
    creditsUrl = "https://github.com/parrotsoft/blog_miguel_lopez_ariza"

    enableMomentJs = true
    

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]